pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    when:
      event: pull_request
    restore: true
    mount:
      - ./pip-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  setup:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: [push, pull_request, tag, deployment]
      branch: develop
    commands:
      - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
      - npm install --depth=0 --quiet
      - pip install -r requirements.txt -r requirements-testing.txt --quiet --cache-dir pip-cache

  npm-build:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: pull_request
    group: testing
    commands:
      - npm run build:prod

  js-lint:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: pull_request
    group: testing
    commands:
      - npm run lint

  python-lint:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: pull_request
    group: testing
    commands:
      - isort -c -rc apps middleware scripts utils
      - flake8 apps middleware scripts utils

  django-tests:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    secrets: [codecov_token]
    when:
      event: [push, pull_request, tag, deployment]
      branch: develop
    group: testing
    commands:
      - py.test --cov=apps
      - pip install codecov --quiet
      - codecov

  rebuild-cache:
    image: drillster/drone-volume-cache
    when:
      event: pull_request
    rebuild: true
    mount:
      - ./pip-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    host: nansen.online.ntnu.no
    port: 22
    username: root
    key: ${SSH_KEY}
    command_timeout: 600
    when:
      event: push
      branch: develop
      status: success
    script:
      - /srv/www/ow4dev/deploy.sh
