pipeline:
  test:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: pull_request
    environment:
      CODECOV_TOKEN: $$CODECOV_TOKEN
    commands:
      - npm install
      - ./node_modules/.bin/eslint assets/js/
      - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
      - tox -e isort
      - tox -e flake8
      - tox -e tests
      - pip install codecov
      - codecov

  deploy:
    image: plugins/ssh
    host: nansen.dotkom
    user: root
    port: 22
    script:
      - /srv/www/ow4dev/deploy.sh
