pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    when:
      event: push
    restore: true
    mount:
      - ./.tox
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  setup:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: push
    commands:
      - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
      - npm install --depth=0 --quiet
      - pip install tox

  npm-build:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: push
    group: testing
    commands:
      - npm run build:prod

  js-lint:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: push
    group: testing
    commands:
      - npm run lint-js

  less-lint:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: push
    group: testing
    commands:
      - npm run lint-less

  python-tests:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    secrets: [codecov_token]
    when:
      event: push
    group: testing
    commands:
      - tox -e tests
      - pip install codecov --quiet
      - codecov

  python-lint:
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    when:
      event: push
    group: testing
    commands:
      - tox -e flake8 -e isort

  rebuild-cache:
    image: drillster/drone-volume-cache
    when:
      event: push
    rebuild: true
    mount:
      - ./.tox
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    host: nansen.online.ntnu.no
    port: 22
    username: root
    key: ${SSH_KEY}
    command_timeout: 600
    when:
      event: push
      branch: develop
      status: success
    script:
      - /srv/www/ow4dev/deploy.sh
