kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    when:
      event:
        - push
    settings:
      restore: true
      mount:
        - ./.tox
        - ./node_modules
      volumes:
        - /tmp/cache:/cache

  - name: setup
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    pull: true
    environment:
      POETRY_VIRTUALENVS_CREATE: false
    when:
      event:
        - push
    commands:
      - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
      - yarn install --pure-lockfile
      - pip install poetry
      - poetry install --no-interaction --no-ansi -E prod
    depends_on:
      - restore-cache

  - name: npm-build
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    when:
      event:
        - push
    group: testing
    commands:
      - npm run build:prod
    depends_on:
     - setup

  - name: js-lint
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    when:
      event:
        - push
    group: testing
    commands:
      - npm run lint-js
    depends_on:
      - setup

  - name: less-lint
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    when:
      event:
        - push
    group: testing
    commands:
      - npm run lint-less
    depends_on:
     - setup

  - name: python-lint
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    when:
      event:
        - push
    group: testing
    commands:
      - poetry run tox -e flake8 -e isort -e black --recreate
    depends_on:
     - setup
     - restore-cache

  - name: python-tests
    image: registry.online.ntnu.no/dotkom/onlineweb4-testbase:3.7
    secrets:
      - codecov_token
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
      OW4_DJANGO_STRIPE_PUBLIC_KEY_ARRKOM:
        from_secret: OW4_DJANGO_STRIPE_PUBLIC_KEY_ARRKOM
      OW4_DJANGO_STRIPE_PUBLIC_KEY_PROKOM:
        from_secret: OW4_DJANGO_STRIPE_PUBLIC_KEY_PROKOM
      OW4_DJANGO_STRIPE_PUBLIC_KEY_TRIKOM:
        from_secret: OW4_DJANGO_STRIPE_PUBLIC_KEY_TRIKOM
      OW4_DJANGO_STRIPE_PRIVATE_KEY_ARRKOM:
        from_secret: OW4_DJANGO_STRIPE_PRIVATE_KEY_ARRKOM
      OW4_DJANGO_STRIPE_PRIVATE_KEY_PROKOM:
        from_secret: OW4_DJANGO_STRIPE_PRIVATE_KEY_PROKOM
      OW4_DJANGO_STRIPE_PRIVATE_KEY_TRIKOM:
        from_secret: OW4_DJANGO_STRIPE_PRIVATE_KEY_TRIKOM
    when:
      event:
        - push
    group: testing
    commands:
      - poetry run tox -e tests --recreate
      - pip install codecov --quiet
      - codecov
    depends_on:
      - setup
      - restore-cache

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    when:
      event:
        - push
    settings:
      rebuild: true
      mount:
        - ./.tox
        - ./node_modules
      volumes:
        - /tmp/cache:/cache
    depends_on:
      - setup
      - python-lint
      - python-tests
      
  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets:
      - ssh_key
    when:
      event:
        - push
      branch: develop
      status: success
    settings:
      host: nansen.online.ntnu.no
      port: 22
      username: root
      key:
        from_secret: ssh_key
      command_timeout: 600s
      script:
        - /srv/www/ow4dev/deploy.sh
    depends_on:
      - npm-build
      - js-lint
      - less-lint
      - python-lint
      - python-tests

image_pull_secrets:
  - dockerconfigjson
