setup_tasks:
  - npm install -g less
  - apt-get install libsasl2-dev

tasks:
  - tox -e flake8
  - tox -e isort
  - tox -e tests
  - tox -e coverage

verbose_tasks:
  - tox -e coverage

coverage:
  path: coverage.xml
  parser: python

