ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      pyenv install 3.7.9 && 
      pyenv global 3.7.9 &&
      pip install poetry &&
      export PIP_USER=false &&
      poetry install &&
      poetry run python manage.py migrate
    command: poetry run python manage.py runserver

github:
  prebuilds:
    addComment: true
    addCheck: true