name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYEMENT_HOST }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: source ${{ secrets.DEPLOY_SCRIPT_LOCATION }}
          timeout: 300s

